model: FlowCF
dataset: ml-1m
gpu_id: '0'
log_wandb: False
wandb_run_name: 'flowcf'

# params for FlowCF
n_steps: 9                           # (int) Discretization steps
s_steps: 2                           # (int) Sampling steps
dims_mlp: [300, 300]                 # (list of int) The dims for the MLP of the flow model
time_embedding_size: 10              # (int) Timestep embedding size

# dataset settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
load_col:
    inter: [user_id, item_id, rating, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"
val_interval: {rating: "[4, inf)"}

# training settings
epochs: 500
train_batch_size: 4096
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
train_neg_sample_args: ~

# evalution settings
metrics: ['Recall', 'NDCG']
valid_metric: NDCG@10
eval_batch_size: 40960000
weight_decay: 0.0
topk: [10, 20]
